--- #YAML:1.0
name:               Net-CouchDb
version:            0.04
abstract:           Interface to CouchDb
author:
    - David Leadbeater <dgl at dgl dot cx>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:      0
    JSON:            2
    LWP::UserAgent:  0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
